# Generated by Django 6.0.2 on 2026-02-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
